### ISSUE TITLE
NULL must be allowed for summary in tl_be_email

### ISSUE THREAD

**Issue by hella-schu** [markocupic/be_email#1]
Hi Marko,
I recently found out that the field summary in tl_be_email should be allowed to be NULL. Otherwise it is not possible to create a new email.
Thanks for changing the attribute.
Best wishes,
Hella

**Comment by markocupic** [comment]
@hella-schu 
Contao Version?

**Comment by markocupic** [comment]
Fixed in version 3.1.13
